services:
  - type: web
    name: collabsphere
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DB_NAME
        value: collabsphere
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URL
        sync: false
